serenity.project.name=OrangeHRM BDD

webdriver.driver=chrome
webdriver.base.url=https://www.google.com
chrome.switches=--start-maximized
webdriver.timeouts.implicitlywait=15000
webdriver.wait.for.timeout=10000
serenity.timeout=15000
serenity.take.screenshots=FOR_FAILURES

dashboard.tag.list=product,team,layer,release,iteration
report.tagtypes=capability,feature
serenity.requirements.custom.field=Requirements
serenity.use.customfield.releases=true
serenity.release.types=Version,Iteration